### ISSUE TITLE
Chromium zTranslate & overflow:hidden

### ISSUE THREAD

**Issue by jd-carroll** [Famous/engine#337]
Do we know if either of these issues have been addressed and if these still impact engine?
- https://github.com/Famous/famous/issues/493
- https://github.com/Famous/famous/issues/621

I know the first issue is marked as fixed, but I am still able to reproduce the issue locally in Chrome 43.
- https://code.google.com/p/chromium/issues/detail?id=421946
- https://code.google.com/p/chromium/issues/detail?id=456601

It is my assumption, neither issue has been addressed and still impacts the `engine` in the same manner as the old library.

**Comment by michaelobriena** [comment]
@jd-carroll 

I will make tests for these but my initial assumptions are that 

https://github.com/Famous/famous/issues/621 has been fixed 
https://github.com/Famous/famous/issues/493 has NOT been fixed

**Comment by michaelobriena** [comment]
#493 has been fixed.  See code here https://github.com/michaelobriena/famous-zindexTest

In a container here https://api-te.famo.us/codemanager/v1/containers/1ba2b818-ea4e-4af9-896c-ccfd555478a9/share

**Comment by michaelobriena** [comment]
#621 has been fixed as the seed project is working.

**Comment by michaelobriena** [comment]
@jd-carroll I will leave this open for a bit so you can confirm if you choose to.

**Comment by jd-carroll** [comment]
Ok, I trust you so I'll go ahead and close.  I am still seeing an overflow issue with the old library, so I'll try porting some of that code to see how it responds.  If I am having any issues, I'll repost here. Thanks!

**Comment by bardu** [comment]
@jd-carroll could you fix your issue with the old library?
